### ISSUE TITLE
Please upload Android 13 (API level 33) jar

### ISSUE THREAD

**Issue by jewelshkjony** [Sable/android-platforms#15]
Please upload Android 13 (API level 33) jar file. I need this for developing app with mit app inventor 2.

**Comment by monperrus** [comment]
that's already in https://github.com/Sable/android-platforms/tree/master/android-13

**Comment by jewelshkjony** [comment]
Please read the topic carefully, I'm talking about Android API level 33 jar

**Comment by jewelshkjony** [comment]
You can download [android-33.jar](https://github.com/jewelshkjony/android-platforms/tree/main/android-33) from here.

**Comment by Wycheproof** [comment]
> You can download [android-33.jar](https://github.com/jewelshkjony/android-platforms/tree/main/android-33) from here.

Thank you.
